ifneq ("$(wildcard 25th-floor.mk)","")
	include 25th-floor.mk
endif

# make
SUBDIRS = $(wildcard */.)

# Define variables, export them and include them usage-documentation
$(eval $(call defw,I_AM_A_VARIABLE,I_AM_THE_VALUE))

.PHONY: all
all: ##@Examples Run all examples
all: example-se

.PHONY: example-se
example-se: ##@Examples How to use $(shell_env)
	@echo '$$(shell_env) my_command'
	$(shell_env) echo "echoing I_AM_A_VARIABLE=$${I_AM_A_VARIABLE}"
